version: '3.11'

services:
  server:
    container_name: fastapi
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn main:api --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - hangman
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - hangman

  frontend:
    container_name: flask-front
    build:
      context: ./frontend
      dockerfile: dockerfile
    volumes:
      - ./frontend/:/frontend/
    expose:
      - 5000
    ports:
      - 5000:5000
    networks:
      - hangman
    depends_on:
      - server

networks:
  hangman:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.27.0/24

volumes:
  postgres_data:
