FROM python:3.9
WORKDIR /api
COPY requirements.txt /api/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /api/
EXPOSE 8000
CMD ["uvicorn", "main:api", "--host", "127.0.0.1", "--port", "8000"]